# Generated by Django 5.2.12 on 2026-03-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcessHoursReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machineries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_activities_min', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('part_date', models.DateField()),
                ('registration_date_utc', models.DateTimeField(auto_now_add=True)),
                ('substitute_start_time', models.TimeField(blank=True, null=True)),
                ('substitute_end_time', models.TimeField(blank=True, null=True)),
                ('excess_hours_justified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('canal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.canal')),
                ('ground', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ground')),
                ('responsible_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_parts', to='core.employee')),
                ('substitute_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitute_parts', to='core.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExcessHoursJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification_text', models.TextField()),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.excesshoursreasons')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartMachinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveIntegerField(blank=True, null=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machineries')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.part')),
            ],
        ),
    ]
